apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: hotel-app
data:
  DATABASE_NAME: mydatabase
  DATABASE_USER: myuser

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: hotel-app
type: Opaque
data:
  DATABASE_PASSWORD: bXlwYXNzd29yZA== # mypassword (base64 encoded)