apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: hotel-app
data:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: myuser

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: hotel-app
type: Opaque
data:
  POSTGRES_PASSWORD: bXlwYXNzd29yZA== # mypassword (base64 encoded)

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: hotel-app
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: hotel-app
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres