# Generated by Django 5.0.3 on 2024-06-06 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('Receptioner', 'REC'), ('Manager', 'MAN'), ('Cleaner', 'CLE')], max_length=100)),
                ('task_description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_number', models.IntegerField()),
                ('bed_number', models.IntegerField()),
                ('have_Terasa', models.BooleanField()),
                ('status_Cleaned', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('isReserved', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.employee')),
                ('room', models.ForeignKey(limit_choices_to={'type': 'cleaner'}, on_delete=django.db.models.deletion.CASCADE, to='hotels_app.room')),
            ],
        ),
    ]
