# Generated by Django 5.0.3 on 2024-06-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels_app.room'),
        ),
        migrations.DeleteModel(
            name='Room_Employee',
        ),
    ]
