# Generated by Django 5.0.3 on 2024-06-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0003_reservation_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='picture',
            new_name='id_picture',
        ),
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
