# Generated by Django 5.0.3 on 2024-06-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0004_rename_picture_reservation_id_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='room',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'Cleaner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels_app.room'),
        ),
    ]
