# Generated by Django 5.0.3 on 2024-06-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0005_alter_employee_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels_app.employee'),
            preserve_default=False,
        ),
    ]
